package com.mattress.model;
// Generated 2016-12-3 21:56:29 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BehaviorSleepAnalysis generated by hbm2java
 */
@Entity
@Table(name = "behavior_sleep_analysis", catalog = "intelligent_mattress")
public class BehaviorSleepAnalysis implements java.io.Serializable {

	private Integer IId;
	private int fkCustomerId;
	private int fkDeviceId;
	private String txContent;
	private String vcKnowledgeId;
	private String vcProductId;

	public BehaviorSleepAnalysis() {
	}

	public BehaviorSleepAnalysis(int fkCustomerId, int fkDeviceId) {
		this.fkCustomerId = fkCustomerId;
		this.fkDeviceId = fkDeviceId;
	}

	public BehaviorSleepAnalysis(int fkCustomerId, int fkDeviceId, String txContent, String vcKnowledgeId,
			String vcProductId) {
		this.fkCustomerId = fkCustomerId;
		this.fkDeviceId = fkDeviceId;
		this.txContent = txContent;
		this.vcKnowledgeId = vcKnowledgeId;
		this.vcProductId = vcProductId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "i_id", unique = true, nullable = false)
	public Integer getIId() {
		return this.IId;
	}

	public void setIId(Integer IId) {
		this.IId = IId;
	}

	@Column(name = "fk_customer_id", nullable = false)
	public int getFkCustomerId() {
		return this.fkCustomerId;
	}

	public void setFkCustomerId(int fkCustomerId) {
		this.fkCustomerId = fkCustomerId;
	}

	@Column(name = "fk_device_id", nullable = false)
	public int getFkDeviceId() {
		return this.fkDeviceId;
	}

	public void setFkDeviceId(int fkDeviceId) {
		this.fkDeviceId = fkDeviceId;
	}

	@Column(name = "tx_content", length = 65535)
	public String getTxContent() {
		return this.txContent;
	}

	public void setTxContent(String txContent) {
		this.txContent = txContent;
	}

	@Column(name = "vc_knowledge_id", length = 50)
	public String getVcKnowledgeId() {
		return this.vcKnowledgeId;
	}

	public void setVcKnowledgeId(String vcKnowledgeId) {
		this.vcKnowledgeId = vcKnowledgeId;
	}

	@Column(name = "vc_product_id", length = 50)
	public String getVcProductId() {
		return this.vcProductId;
	}

	public void setVcProductId(String vcProductId) {
		this.vcProductId = vcProductId;
	}

}
