package com.mattress.model;
// Generated 2016-12-3 21:56:29 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BehaviorSleepHabits generated by hbm2java
 */
@Entity
@Table(name = "behavior_sleep_habits", catalog = "intelligent_mattress")
public class BehaviorSleepHabits implements java.io.Serializable {

	private Integer IId;
	private int fkCustomerId;
	private int fkDeviceId;
	private Date TOnbedTime;
	private Date TOffbedTime;

	public BehaviorSleepHabits() {
	}

	public BehaviorSleepHabits(int fkCustomerId, int fkDeviceId) {
		this.fkCustomerId = fkCustomerId;
		this.fkDeviceId = fkDeviceId;
	}

	public BehaviorSleepHabits(int fkCustomerId, int fkDeviceId, Date TOnbedTime, Date TOffbedTime) {
		this.fkCustomerId = fkCustomerId;
		this.fkDeviceId = fkDeviceId;
		this.TOnbedTime = TOnbedTime;
		this.TOffbedTime = TOffbedTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "i_id", unique = true, nullable = false)
	public Integer getIId() {
		return this.IId;
	}

	public void setIId(Integer IId) {
		this.IId = IId;
	}

	@Column(name = "fk_customer_id", nullable = false)
	public int getFkCustomerId() {
		return this.fkCustomerId;
	}

	public void setFkCustomerId(int fkCustomerId) {
		this.fkCustomerId = fkCustomerId;
	}

	@Column(name = "fk_device_id", nullable = false)
	public int getFkDeviceId() {
		return this.fkDeviceId;
	}

	public void setFkDeviceId(int fkDeviceId) {
		this.fkDeviceId = fkDeviceId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "t_onbed_time", length = 19)
	public Date getTOnbedTime() {
		return this.TOnbedTime;
	}

	public void setTOnbedTime(Date TOnbedTime) {
		this.TOnbedTime = TOnbedTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "t_offbed_time", length = 19)
	public Date getTOffbedTime() {
		return this.TOffbedTime;
	}

	public void setTOffbedTime(Date TOffbedTime) {
		this.TOffbedTime = TOffbedTime;
	}

}
