package com.mattress.model;
// Generated 2016-12-3 21:56:29 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BehaviorOperateRecord generated by hbm2java
 */
@Entity
@Table(name = "behavior_operate_record", catalog = "intelligent_mattress")
public class BehaviorOperateRecord implements java.io.Serializable {

	private Integer IId;
	private int fkCustomerId;
	private int fkDeviceId;
	private Byte tiStatus;
	private Date TTime;
	private String vcTemperature;

	public BehaviorOperateRecord() {
	}

	public BehaviorOperateRecord(int fkCustomerId, int fkDeviceId) {
		this.fkCustomerId = fkCustomerId;
		this.fkDeviceId = fkDeviceId;
	}

	public BehaviorOperateRecord(int fkCustomerId, int fkDeviceId, Byte tiStatus, Date TTime, String vcTemperature) {
		this.fkCustomerId = fkCustomerId;
		this.fkDeviceId = fkDeviceId;
		this.tiStatus = tiStatus;
		this.TTime = TTime;
		this.vcTemperature = vcTemperature;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "i_id", unique = true, nullable = false)
	public Integer getIId() {
		return this.IId;
	}

	public void setIId(Integer IId) {
		this.IId = IId;
	}

	@Column(name = "fk_customer_id", nullable = false)
	public int getFkCustomerId() {
		return this.fkCustomerId;
	}

	public void setFkCustomerId(int fkCustomerId) {
		this.fkCustomerId = fkCustomerId;
	}

	@Column(name = "fk_device_id", nullable = false)
	public int getFkDeviceId() {
		return this.fkDeviceId;
	}

	public void setFkDeviceId(int fkDeviceId) {
		this.fkDeviceId = fkDeviceId;
	}

	@Column(name = "ti_status")
	public Byte getTiStatus() {
		return this.tiStatus;
	}

	public void setTiStatus(Byte tiStatus) {
		this.tiStatus = tiStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "t_time", length = 19)
	public Date getTTime() {
		return this.TTime;
	}

	public void setTTime(Date TTime) {
		this.TTime = TTime;
	}

	@Column(name = "vc_temperature", length = 50)
	public String getVcTemperature() {
		return this.vcTemperature;
	}

	public void setVcTemperature(String vcTemperature) {
		this.vcTemperature = vcTemperature;
	}

}
