package com.mattress.model;
// Generated 2016-12-3 21:56:29 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeviceInfo generated by hbm2java
 */
@Entity
@Table(name = "device_info", catalog = "intelligent_mattress")
public class DeviceInfo implements java.io.Serializable {

	private Integer IId;
	private String vcName;
	private Integer IStatus;
	private Date TTime;

	public DeviceInfo() {
	}

	public DeviceInfo(String vcName, Integer IStatus, Date TTime) {
		this.vcName = vcName;
		this.IStatus = IStatus;
		this.TTime = TTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "i_id", unique = true, nullable = false)
	public Integer getIId() {
		return this.IId;
	}

	public void setIId(Integer IId) {
		this.IId = IId;
	}

	@Column(name = "vc_name", length = 50)
	public String getVcName() {
		return this.vcName;
	}

	public void setVcName(String vcName) {
		this.vcName = vcName;
	}

	@Column(name = "i_status")
	public Integer getIStatus() {
		return this.IStatus;
	}

	public void setIStatus(Integer IStatus) {
		this.IStatus = IStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "t_time", length = 10)
	public Date getTTime() {
		return this.TTime;
	}

	public void setTTime(Date TTime) {
		this.TTime = TTime;
	}

}
