package com.mattress.model;
// Generated 2016-12-3 21:56:29 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * KnowledgeInfo generated by hbm2java
 */
@Entity
@Table(name = "knowledge_info", catalog = "intelligent_mattress")
public class KnowledgeInfo implements java.io.Serializable {

	private Integer IId;
	private String vcLabelId;
	private String vcTitle;
	private String txContent;
	private String vcLink;

	public KnowledgeInfo() {
	}

	public KnowledgeInfo(String vcLabelId, String vcTitle, String txContent, String vcLink) {
		this.vcLabelId = vcLabelId;
		this.vcTitle = vcTitle;
		this.txContent = txContent;
		this.vcLink = vcLink;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "i_id", unique = true, nullable = false)
	public Integer getIId() {
		return this.IId;
	}

	public void setIId(Integer IId) {
		this.IId = IId;
	}

	@Column(name = "vc_label_id", length = 50)
	public String getVcLabelId() {
		return this.vcLabelId;
	}

	public void setVcLabelId(String vcLabelId) {
		this.vcLabelId = vcLabelId;
	}

	@Column(name = "vc_title", length = 50)
	public String getVcTitle() {
		return this.vcTitle;
	}

	public void setVcTitle(String vcTitle) {
		this.vcTitle = vcTitle;
	}

	@Column(name = "tx_content", length = 65535)
	public String getTxContent() {
		return this.txContent;
	}

	public void setTxContent(String txContent) {
		this.txContent = txContent;
	}

	@Column(name = "vc_link", length = 200)
	public String getVcLink() {
		return this.vcLink;
	}

	public void setVcLink(String vcLink) {
		this.vcLink = vcLink;
	}

}
