package com.mattress.model;
// Generated 2016-12-3 21:56:29 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Label generated by hbm2java
 */
@Entity
@Table(name = "label", catalog = "intelligent_mattress")
public class Label implements java.io.Serializable {

	private Integer IId;
	private String vcName;
	private Byte tiType;

	public Label() {
	}

	public Label(String vcName, Byte tiType) {
		this.vcName = vcName;
		this.tiType = tiType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "i_id", unique = true, nullable = false)
	public Integer getIId() {
		return this.IId;
	}

	public void setIId(Integer IId) {
		this.IId = IId;
	}

	@Column(name = "vc_name", length = 50)
	public String getVcName() {
		return this.vcName;
	}

	public void setVcName(String vcName) {
		this.vcName = vcName;
	}

	@Column(name = "ti_type")
	public Byte getTiType() {
		return this.tiType;
	}

	public void setTiType(Byte tiType) {
		this.tiType = tiType;
	}

}
