package com.mattress.model;
// Generated 2016-12-3 21:56:29 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductInfo generated by hbm2java
 */
@Entity
@Table(name = "product_info", catalog = "intelligent_mattress")
public class ProductInfo implements java.io.Serializable {

	private Integer IId;
	private String vcLabelId;
	private String vcName;
	private String vcIntroduction;
	private Float FPrice;
	private String vcImageUrl;

	public ProductInfo() {
	}

	public ProductInfo(String vcLabelId, String vcName, String vcIntroduction, Float FPrice, String vcImageUrl) {
		this.vcLabelId = vcLabelId;
		this.vcName = vcName;
		this.vcIntroduction = vcIntroduction;
		this.FPrice = FPrice;
		this.vcImageUrl = vcImageUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "i_id", unique = true, nullable = false)
	public Integer getIId() {
		return this.IId;
	}

	public void setIId(Integer IId) {
		this.IId = IId;
	}

	@Column(name = "vc_label_id", length = 50)
	public String getVcLabelId() {
		return this.vcLabelId;
	}

	public void setVcLabelId(String vcLabelId) {
		this.vcLabelId = vcLabelId;
	}

	@Column(name = "vc_name", length = 50)
	public String getVcName() {
		return this.vcName;
	}

	public void setVcName(String vcName) {
		this.vcName = vcName;
	}

	@Column(name = "vc_introduction", length = 65535)
	public String getVcIntroduction() {
		return this.vcIntroduction;
	}

	public void setVcIntroduction(String vcIntroduction) {
		this.vcIntroduction = vcIntroduction;
	}

	@Column(name = "f_price", precision = 6, scale = 0)
	public Float getFPrice() {
		return this.FPrice;
	}

	public void setFPrice(Float FPrice) {
		this.FPrice = FPrice;
	}

	@Column(name = "vc_image_url", length = 200)
	public String getVcImageUrl() {
		return this.vcImageUrl;
	}

	public void setVcImageUrl(String vcImageUrl) {
		this.vcImageUrl = vcImageUrl;
	}

}
