package com.mattress.model;
// Generated 2016-12-3 21:56:29 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserBindDevice generated by hbm2java
 */
@Entity
@Table(name = "user_bind_device", catalog = "intelligent_mattress")
public class UserBindDevice implements java.io.Serializable {

	private Integer IId;
	private int fkCustomerId = 0;
	private int fkDeviceId = 0;
	private String vcName = "新设备";
	private Date TTime = new Date();
	private Byte tiStatus = 1;

	public UserBindDevice() {
	}

	public UserBindDevice(int fkCustomerId, int fkDeviceId) {
		this.fkCustomerId = fkCustomerId;
		this.fkDeviceId = fkDeviceId;
	}

	public UserBindDevice(int fkCustomerId, int fkDeviceId, String vcName, Date TTime, Byte tiStatus) {
		this.fkCustomerId = fkCustomerId;
		this.fkDeviceId = fkDeviceId;
		this.vcName = vcName;
		this.TTime = TTime;
		this.tiStatus = tiStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "i_id", unique = true, nullable = false)
	public Integer getIId() {
		return this.IId;
	}

	public void setIId(Integer IId) {
		this.IId = IId;
	}

	@Column(name = "fk_customer_id", nullable = false)
	public int getFkCustomerId() {
		return this.fkCustomerId;
	}

	public void setFkCustomerId(int fkCustomerId) {
		this.fkCustomerId = fkCustomerId;
	}

	@Column(name = "fk_device_id", nullable = false)
	public int getFkDeviceId() {
		return this.fkDeviceId;
	}

	public void setFkDeviceId(int fkDeviceId) {
		this.fkDeviceId = fkDeviceId;
	}

	@Column(name = "vc_name", length = 50)
	public String getVcName() {
		return this.vcName;
	}

	public void setVcName(String vcName) {
		this.vcName = vcName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "t_time", length = 19)
	public Date getTTime() {
		return this.TTime;
	}

	public void setTTime(Date TTime) {
		this.TTime = TTime;
	}

	@Column(name = "ti_status")
	public Byte getTiStatus() {
		return this.tiStatus;
	}

	public void setTiStatus(Byte tiStatus) {
		this.tiStatus = tiStatus;
	}

}
