package com.mattress.model;
// Generated 2016-12-3 21:56:29 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserCustomerPlatform generated by hbm2java
 */
@Entity
@Table(name = "user_customer_platform", catalog = "intelligent_mattress")
public class UserCustomerPlatform implements java.io.Serializable {

	private Integer IId;
	private int fkCustomerId;
	private Integer IPlatformId;
	private String vcName;

	public UserCustomerPlatform() {
	}

	public UserCustomerPlatform(int fkCustomerId) {
		this.fkCustomerId = fkCustomerId;
	}

	public UserCustomerPlatform(int fkCustomerId, Integer IPlatformId, String vcName) {
		this.fkCustomerId = fkCustomerId;
		this.IPlatformId = IPlatformId;
		this.vcName = vcName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "i_id", unique = true, nullable = false)
	public Integer getIId() {
		return this.IId;
	}

	public void setIId(Integer IId) {
		this.IId = IId;
	}

	@Column(name = "fk_customer_id", nullable = false)
	public int getFkCustomerId() {
		return this.fkCustomerId;
	}

	public void setFkCustomerId(int fkCustomerId) {
		this.fkCustomerId = fkCustomerId;
	}

	@Column(name = "i_platform_id")
	public Integer getIPlatformId() {
		return this.IPlatformId;
	}

	public void setIPlatformId(Integer IPlatformId) {
		this.IPlatformId = IPlatformId;
	}

	@Column(name = "vc_name", length = 50)
	public String getVcName() {
		return this.vcName;
	}

	public void setVcName(String vcName) {
		this.vcName = vcName;
	}

}
